### ISSUE TITLE
Vacuum cleaner not available version operating system 7.5

### ISSUE THREAD

**Issue by Falonsob86** [nergal/homeassistant-vacuum-viomi#32]
Hello,
after upgrading the operating system to version 7.5, the vacuum cleaner has become unavailable.
The HA log is as follows:

Error while setting up xiaomi_viomi platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_viomi/vacuum.py", line 54, in async_setup_platform
    config = await validate_input(hass, raw_config)
  File "/config/custom_components/xiaomi_viomi/config_flow.py", line 86, in validate_input
    raise InvalidAuth
custom_components.xiaomi_viomi.config_flow.InvalidAuth

Thank you

**Comment by Falonsob86** [comment]
Works after reboot several times
