### ISSUE TITLE
Error while setting up xiaomi_viomi platform for vacuum (missing 2 required keyword-only arguments: 'options' and 'unique_id'

### ISSUE THREAD

**Issue by Turntable67** [nergal/homeassistant-vacuum-viomi#53]
2024-07-12 15:49:37.397 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up xiaomi_viomi platform for vacuum
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/xiaomi_viomi/vacuum.py", line 55, in async_setup_platform
entry = ConfigEntry(
^^^^^^^^^^^^
TypeError: ConfigEntry.__init__() missing 2 required keyword-only arguments: 'options' and 'unique_id'

**Comment by Turntable67** [comment]
Fixed this by adding these missing arguments to the vacuum.py

entry = ConfigEntry(
        domain=PLATFORM_NAME,
        data=config,
        version=2,
        title=config[CONF_NAME],
        source=SOURCE_USER,
        **options={},  # Add default or specific options here
        unique_id=config.get(CONF_NAME, "xiaomi_viomi_vacuum"),  # Provide a unique identifier**
    )
